name: ddc-fcs
services:
  server:
    image: docker.zdl.org/ddc-fcs:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
    restart: ${DDC_FCS_RESTART:-no}
    environment:
      - "DDC_FCS_HTTP_PROTOCOL=https"
      - "DDC_FCS_HTTP_HOST=clarin.bbaw.de"
      - "DDC_FCS_HTTP_PORT=443"
      - "DDC_FCS_HTTP_CONTEXT_PATH=/fcs"
      - "DDC_FCS_HTTP_SERVER_PORT=9090"
    ports:
      - "9090:9090"
